services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis

  nextcloud:
    image: nextcloud
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis

volumes:
  db_data: